spring.application.name=SE2

server.port=9000

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/se2-new
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

#server.error.include-message=always
#server.error.include-stacktrace=always
#server.error.include-exception=true

logging.file.name=app.log

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-mater.yaml
