spring.application.name=SE2
server.port=9000
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/se2
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.error.include-message=always
#server.error.include-stacktrace=always
#server.error.include-exception=true
logging.file.name=app.log
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-mater.yaml
GITHUB_CLIENT_ID=Ov23lifaGyhLzgEUkVuk
GITHUB_CLIENT_SECRET=5d0dacf4385e8f401169577f826b4bb9b5b80710
GOOGLE_CLIENT_ID=161590022492-l9t2lqhtssn21buedu9eldg8qorshhrp.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
MAIL_USERNAME=Tranhunghp22112004@gmail.com
MAIL_PASSWORD=xlewrwnkolwikvmp