-- H2-compatible schema for dev profile

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    phone VARCHAR(255),
    avatar VARCHAR(255),
    is_logged_in BOOLEAN DEFAULT FALSE,
    provider VARCHAR(255),
    reset_password_token VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_role (
    user_id VARCHAR(255),
    role_id BIGINT,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) UNIQUE,
    status BOOLEAN,
    description CLOB,
    content CLOB,
    author VARCHAR(255),
    image VARCHAR(255),
    embedding VARBINARY(4096)
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS category_book (
    category_id BIGINT,
    book_id BIGINT,
    PRIMARY KEY (category_id, book_id)
);

-- Seed data
INSERT INTO roles (id, name) VALUES (1, 'SUPER_ADMIN');
INSERT INTO roles (id, name) VALUES (2, 'USER');

INSERT INTO users (id, first_name, last_name, email, password, provider, is_logged_in)
VALUES ('admin-001', 'Admin', 'User', 'admin@gmail.com', '{bcrypt}$2a$10$dummyhashnotreal00000000000000000000000000000000000', 'LOCAL', false);

INSERT INTO user_role (user_id, role_id) VALUES ('admin-001', 1);
